### PR TITLE
Release rancher-turtles 0.4.0

### PR DESCRIPTION
**Pull request by hardys**
This aligns with the [0.13 upstream Rancher turtles release](https://github.com/rancher/turtles/releases/tag/v0.13.0), and updates [CAPM3 to 1.7.2](https://github.com/metal3-io/cluster-api-provider-metal3/releases/tag/v1.7.2)

### CODE REVIEW

**Review by alknopfler — APPROVED** [review]
LGTM

**Comment by hardys** [comment]
I found an issue with the airgap CM's - we're pulling the upstream images so will revert this to draft while I work on a fix

**Comment by hardys** [comment]
The image/version issues should now be resolved:

```
> for n in rke2-bootstrap-system rke2-control-plane-system capi-system capm3-system rancher-turtles-system; do kubectl get deployment -n $n -o yaml | grep image: ; done
          image: registry.rancher.com/rancher/cluster-api-provider-rke2-bootstrap:v0.8.0
          image: registry.rancher.com/rancher/cluster-api-provider-rke2-controlplane:v0.8.0
          image: registry.rancher.com/rancher/cluster-api-controller:v1.7.7
          image: registry.opensuse.org/isv/suse/edge/clusterapi/containers/images/cluster-api-provider-metal3:1.7.2
          image: registry.opensuse.org/isv/suse/edge/clusterapi/containers/images/ip-address-manager:1.7.2
          image: registry.rancher.com/rancher/cluster-api-operator:v0.14.0
          image: registry.rancher.com/rancher/rancher/turtles:v0.13.0
```

**Review by fdegir — APPROVED** [review]
This passed SV!

**Pull request merged**
