### PR TITLE
Update images and chart of SRIOV

### PR DESCRIPTION
**Pull request by manuelbuil**
This PR does a sweeping version bump in all the SRIOV related projects:
* Moves the chart to "latest". Unfortunately, there has not been an official release since July 2022, so we need to use the commit. We bumped the version almost 2 years and we are pointing now at the latest commit
* operator, sriovConfigDaemon move to `v1.2.0-build20240327`
* sriovCni moves to `v2.7.0-build20240327`
* ibSriovCni moves to  `v1.0.3-build20240327`
* sriovDevicePlugin moves to ` v3.6.2-build20240327`
* resourcesInjector moves to ` v1.5-build20240327`

We would be using more up to date code and images, which provides important benefits such as reducing CVEs to 0

We are creating new charts/assets with version v1.2.0

### CODE REVIEW

**Review by Kristian-ZH — APPROVED** [review]
/lgtm

Let's wait for one more approval before merging the PR

**Comment by manuelbuil** [comment]
We are going to do an extra update to remove all CVEs of the opreator

**Comment by manuelbuil** [comment]
PR ready again. Number of CVEs 0! We tested in our lab and it works

**Comment by manuelbuil** [comment]
@alknopfler could you give it a try at your end just to be sure it works with your usecase?

**Review by Kristian-ZH — APPROVED** [review]
I tested the PR one more time and all the pods were successfully deployed in the cluster and were running so I'm merging the PR.

**Comment by alknopfler** [comment]
Tested with Kris and now it's easy to pass new nics:
helm install sriov-network-operator . --set supportedExtraNICs[0]="MyNIC: 8086 1521 1520" --set supportedExtraNICs[1]="MyNIC2: 8086 1521 1520"

also it's possible with the helm-values file 
thanks @Kristian-ZH for your test and @manuelbuil for the PR

**Pull request merged**
