### PR TITLE
Release Metal3 0.9.0

### PR DESCRIPTION
**Pull request by hardys**
This is a major update containing the following changes:

- Ironic dependencies are rebased to the latest [2024.2 stable OpenStack branch](https://files.openstack.org/docs/releasenotes/ironic/2024.2.html)
- The ironic container has been rebased to more closely align with the upstream [metal3-io ironic-image](https://github.com/metal3-io/ironic-image) which includes several fixes and security improvements, removal of the deprecated `idrac-wsman` driver, removal of the ironic-inspector, and enablement of sqlite as an alternative to mariadb
- The metal3 baremetal-operator has been updated to the [0.8.0 upstream release](https://github.com/metal3-io/baremetal-operator/releases/tag/v0.8.0), and the deployment reconfigured to remove the dependency on ironic-inspector (inspection is now handled via the ironic API)
- Mariadb is now optional and disabled by default, on upgrade the mariadb deployment will be replaced by sqlite unless the new `enable_mariadb` variable is specified. 
- Persistent storage for the Ironic shared volume is now optional and disabled by default - on upgrade it will be necessary to ensure the `size` and `storageClass` persistence values are specified if you wish to retain a PVC in the deployment
- The IPA ramdisk now supports a `hosts.append` parameter which can be passed via the `ironicKernelParams` chart value, e.g `hosts.append=192.168.125.99_imagecache.local` - this is comma-delimited and the `_` will be translated into spaces, with each entry then appended to `/etc/hosts` - this is related to [this Sylva issue](https://gitlab.com/sylva-projects/sylva-core/-/issues/1653)

### CODE REVIEW

**Comment by hardys** [comment]
Marking this as draft pending further validation - @fdegir FYI there is a preview published at https://hardys.github.io/charts/

**Review by Kristian-ZH — APPROVED** [review]
/LGTM
The chart was validated with SV

**Review by dprodanov4 — APPROVED** [review]
lgtm!

**Comment by hardys** [comment]
I will ask for validation in Sylva CI before we merge this but removed the draft status based on feedback above

**Comment by hardys** [comment]
> > The metal3 baremetal-operator has been updated to the [0.8.0 upstream release](https://github.com/metal3-io/baremetal-operator/releases/tag/v0.8.0), and the deployment reconfigured to remove the dependency on ironic-inspector (inspection is now handled via the ironic API)
> 
> I understand that Ironic port tcp/5050 is no more used and inspection flow now uses port tcp/6385. Am I right ?

Hi @greenmaid yes that's correct - following the upstream Ironic community decision to [deprecate](https://specs.openstack.org/openstack/ironic-specs/specs/approved/merge-inspector.html) the standalone ironic-inspector API the [Metal3 upstream community agreed](https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/inspector-deprecation.md) to make changes to align and use the [inventory API](https://docs.openstack.org/api-ref/baremetal/#show-node-inventory) that is part of the main Ironic API instead

**Comment by hardys** [comment]
Sylva validation of this was successful so I'll go ahead and merge this https://gitlab.com/sylva-projects/sylva-core/-/merge_requests/3297

**Pull request merged**
