### PR TITLE
Migrated the metal3 helm charts from the rancher-sandbox org

### PR DESCRIPTION
**Pull request by jdob**
We want all of the charts we'll be supporting in our org. These were originally done by the Systems Engineering team in the rancher-sandbox org, so this PR is the initial copy into our org.

### CODE REVIEW

**Comment by dbw7** [comment]
LGMT

**Comment by rdoxenham** [comment]
LGTM

**Comment by e-minguez** [comment]
Just a nit, the [README.md](https://github.com/suse-edge/charts/blob/main/README.md) file needs to be manually modified to include the new chart as well.

**Comment by jdob** [comment]
Closing this out in favor of Danny's implementation

**Pull request closed without merging**
