### PR TITLE
Logos have moved it seems

### PR DESCRIPTION
**Pull request by e-minguez**

### CODE REVIEW

**Review by diconico07 — APPROVED** [review]

**Comment by hardys** [comment]
I think we also need to update the archive e.g `helm package charts/metal3-deploy/0.1.0/ -d assets/metal3-deploy` (until we resolve the [issue preventing using chart-build-scripts for that](https://github.com/rancher/charts-build-scripts/pull/106) ?

**Comment by e-minguez** [comment]
> I think we also need to update the archive e.g `helm package charts/metal3-deploy/0.1.0/ -d assets/metal3-deploy` (until we resolve the [issue preventing using chart-build-scripts for that](https://github.com/rancher/charts-build-scripts/pull/106) ) ?

I think I did it (?) there is no reference to "cncf-branding.netlify.app" in the updated file (unless you are talking about anything different)

**Comment by hardys** [comment]
> > I think we also need to update the archive e.g `helm package charts/metal3-deploy/0.1.0/ -d assets/metal3-deploy` (until we resolve the [issue preventing using chart-build-scripts for that](https://github.com/rancher/charts-build-scripts/pull/106) ) ?
> 
> I think I did it (?) there is no reference to "cncf-branding.netlify.app" in the updated file (unless you are talking about anything different)

Maybe I'm missing something - AFAICS the tarball isn't updated by this PR, so if you untar `assets/metal3-deploy/ metal3-deploy-0.1.0.tgz` we still see the old path e.g:

```
./metal3-deploy/0.1.0/Chart.yaml:icon: https://cncf-branding.netlify.app/img/projects/metal3/icon/color/metal3-icon-color.svg
```

**Comment by e-minguez** [comment]
> > > I think we also need to update the archive e.g `helm package charts/metal3-deploy/0.1.0/ -d assets/metal3-deploy` (until we resolve the [issue preventing using chart-build-scripts for that](https://github.com/rancher/charts-build-scripts/pull/106) ) ?
> > 
> > 
> > I think I did it (?) there is no reference to "cncf-branding.netlify.app" in the updated file (unless you are talking about anything different)
> 
> Maybe I'm missing something - AFAICS the tarball isn't updated by this PR, so if you untar `assets/metal3-deploy/ metal3-deploy-0.1.0.tgz` we still see the old path e.g:
> 
> ```
> ./metal3-deploy/0.1.0/Chart.yaml:icon: https://cncf-branding.netlify.app/img/projects/metal3/icon/color/metal3-icon-color.svg
> ```

Apologizes, I wasn't taking into account the tarball 🤦🏻 In any case, as this is just cosmetic (to fix the current index.html here https://suse-edge.github.io/charts/ ) and give the fact that you probably will release a new version soon, I'm not sure if creating the tarball is required or it will be _inherit_ next time a release is done 😅

**Pull request merged**
