### PR TITLE
Add defaults for the Ironic service endpoints

### PR DESCRIPTION
**Pull request by Kristian-ZH**
Add defaults for the Ironic service endpoints.
This will fix an issue introduced in the previous PR where if the vars in the PR are not provided, the installation will fail

### CODE REVIEW

**Comment by hardys** [comment]
We discussed this on slack, and it appears to be required only for the case where sub charts are installed directly such as in the [metal3-demo environment](https://github.com/suse-edge/metal3-demo/blob/main/roles/baremetal/tasks/main.yml#L79)

I'm not sure if that's really a use-case we want to support, but the fix here seems OK if we want to proceed without making changes to the metal3-demo repo - before we can merge the archive needs to be updated though.

IMO we should consider reworking the demo automation so it just installs the top-level chart, then we'll get the global defaults, and I think it's better aligned with the usage we want/expect to support?

@Kristian-ZH @atanasdinov what are your thoughts, should we proceed with this or fix the demo repo?

**Comment by Kristian-ZH** [comment]
fixing the demo repo sounds better to me

**Comment by atanasdinov** [comment]
I agree with both of you. I was not familiar with the issue earlier but we shouldn't provide workarounds for unexpected chart usages.

**Comment by Kristian-ZH** [comment]
As we took the decision to fix the issue in the metal3-demo, I will close this PR.

**Pull request closed without merging**
