### PR TITLE
Release SR-IOV `v1.4.0`

### PR DESCRIPTION
**Pull request by mgfritch**
Update to the latest SR-IOV and node-feature-discovery release:

- sriov-network-operator `v1.4.0`
- sriov-nfd `v0.15.7`

Remove (currently) unsupported features:
- RDMA CNI
- Network Metrics Exporter

### CODE REVIEW

**Comment by alknopfler** [comment]
@fdegir Could you please test it in SV to validate the new version?

**Comment by alknopfler** [comment]
Looks good to me
/LGTM

**Review by hardys — APPROVED** [review]
lgtm, thanks for taking care of this!

**Review by alknopfler — APPROVED** [review]

**Review by fdegir — APPROVED** [review]
Apologies for delayed response but we tested this PR and it looks good.

**Pull request merged**
