### PR TITLE
Release Metal3 0.8.0

### PR DESCRIPTION
**Pull request by hardys**
This is a major update which rebases several images:

* Ironic + dependencies are rebased to the 2024.1 stable release
* baremetal-operator is rebased to the 0.6.1 release
    * *Note* this includes some CRD additions which will require manual apply on upgrade
* The IPA ramdisk has been rebased to 2024.1 IPA and 15.6 OS version

All images are now also based on the 15.6 BCI image - for more details see https://build.opensuse.org/project/show/isv:SUSE:Edge:Metal3:Ironic:2024.1

This is ready for review but marked WIP pending further testing

### CODE REVIEW

**Comment by hardys** [comment]
Marking this as a draft - it's missing some CRD updates related to the new baremetal-operator version

**Comment by hardys** [comment]
@Kristian-ZH @alknopfler - this is now working in my VM test environment, please could you review and help verify on baremetal when you get some time, thanks!

**Comment by hardys** [comment]
I found one issue testing upgrade from 0.7.2 - due to the difference in mariadb version we can encounter this:

```
2024-07-18 13:47:23 0 [Note] Starting MariaDB 10.11.6-MariaDB source revision fecd78b83785d5ae96f2c6ff340375be803cd299 as process 129
2024-07-18 13:47:23 0 [Warning] option 'innodb-log-buffer-size': unsigned value 524288 adjusted to 2097152
2024-07-18 13:47:23 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
2024-07-18 13:47:23 0 [Note] InnoDB: Number of transaction pools: 1
2024-07-18 13:47:23 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2024-07-18 13:47:23 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2024-07-18 13:47:23 0 [Note] InnoDB: Using Linux native AIO
2024-07-18 13:47:23 0 [Note] InnoDB: Initializing buffer pool, total size = 5.000MiB, chunk size = 1.000MiB
2024-07-18 13:47:23 0 [Note] InnoDB: Completed initialization of buffer pool
2024-07-18 13:47:23 0 [Note] InnoDB: Buffered log writes (block size=512 bytes)
2024-07-18 13:47:23 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.6.15. You must start up and shut down MariaDB 10.7 or earlier.
2024-07-18 13:47:23 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2024-07-18 13:47:23 0 [Note] InnoDB: Starting shutdown...
2024-07-18 13:47:24 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-07-18 13:47:24 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-07-18 13:47:24 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2024-07-18 13:47:24 0 [ERROR] Aborting
```

The workaround is simply to remove the mariadb deployment and pvc, since the DB content is re-created anyway, but probably we need to find a way to more robustly handle this inside the mariadb container itself (for example erasing the DB on container startup, but if we do that it might make more sense to just switch to sqlite which was previously discussed...)

**Comment by alknopfler** [comment]
Tested in lab with baremetal working fine (available OK, and the capi provision phase OK too):
```
default     lab-xr11-3     provisioned   xr11-3-cluster2-controlplane-bxcpz   true             24m
```

**Review by alknopfler — APPROVED** [review]
/LGTM

**Comment by hardys** [comment]
To unblock progress I've dropped the mariadb update from this PR - that requires further investigation and we can continue with the other Ironic/Metal3 updates as a first step

**Review by Kristian-ZH — APPROVED** [review]
Successfully provisioned a BM machine is SV

**Pull request merged**
