### PR TITLE
add rancher turtle chart

### PR DESCRIPTION
**Pull request by alknopfler**
This PR includes the rancher-turtle chart as a wrapper to include metal3 infra provider as well as using our suse-edge images:
- just modifying the templates/clusterctl-configmap with the providers as we're doing now, the values.yaml file will be completed during provisioning phase
- Tested in lab
```
mgmt-cluster-network:~/charts/charts/rancher-turtles/0.1.0+up0.9.1 # k get capiproviders -A
NAMESPACE                   NAME                 TYPE             PROVIDERNAME   INSTALLEDVERSION   PHASE
capi-system                 cluster-api          core             cluster-api    v1.6.2             Ready
capm3-system                metal3               infrastructure   metal3         v1.6.0             Ready
rke2-bootstrap-system       rke2-bootstrap       bootstrap        rke2           v0.2.6             Ready
rke2-control-plane-system   rke2-control-plane   controlPlane     rke2           v0.2.6             Ready 
```
```
NAMESPACE                   NAME                                                     READY   STATUS      RESTARTS        AGE
capi-system                 capi-controller-manager-6d85f8bd7-5nlxn                  1/1     Running     0               35s
capm3-system                capm3-controller-manager-58b9ccdb45-hmwxs                1/1     Running     0               5s
capm3-system                ipam-controller-manager-96b9bb87c-ckl5t                  1/1     Running     0               5s
```
```
rke2-bootstrap-system       rke2-bootstrap-controller-manager-67664b5f99-qw29h       1/1     Running     0               7s
rke2-control-plane-system   rke2-control-plane-controller-manager-75c8bcb68f-v77sc   1/1     Running     0               7s 
```
and tested also in VMs to deploy and provision a VM:
```
mgmt-cluster-network:~ # k get bmh -A
NAMESPACE   NAME           STATE         CONSUMER                                 ONLINE   ERROR   AGE
default     flexran-demo   provisioned   single-node-cluster-controlplane-d78z5   true             20m
```

### CODE REVIEW

**Review by Kristian-ZH — APPROVED** [review]

**Comment by Kristian-ZH** [comment]
The CI is failing with
```
time="2024-07-30T13:27:32Z" level=info msg="Checking if Git is clean after generating charts"
time="2024-07-30T13:27:32Z" level=warning msg="Generated charts produced the following changes in Git.\n M charts/rancher-turtles/0.1.0+up0.9.1/templates/clusterctl-config.yaml\n"
time="2024-07-30T13:27:32Z" level=fatal msg="Please commit these changes and run validation again."
```

**Comment by Kristian-ZH** [comment]
It runs `make validate` so you can check this locally

**Comment by alknopfler** [comment]
solved @Kristian-ZH

**Comment by Kristian-ZH** [comment]
Nice! 
/LGTM

**Pull request merged**
