### PR TITLE
Update metallb version to v0.14.3

### PR DESCRIPTION
**Pull request by Kristian-ZH**
Align MetalLB with the upstream version: v0.14.3.

This PR also introduces a new component called `frr-k8s` - https://github.com/metallb/frr-k8s

### CODE REVIEW

**Comment by rdoxenham** [comment]
Thanks for this @Kristian-ZH - I'm asking @atanasdinov to take a look also as we need to validate functionality for multi-node k8s as we use this for establishing multi-node clusters via EIB.

**Review by atanasdinov — APPROVED** [review]
LGTM! It's easier for me to test this in EIB once it's in main so I'm good with merging this as is and coming back to it later if necessary.

**Comment by Kristian-ZH** [comment]
@atanasdinov you can test it with this helm repo: https://kristian-zh.github.io/charts

**Comment by atanasdinov** [comment]
I didn't know that the repository is transferred over for forks. Thanks!

**Comment by Kristian-ZH** [comment]
It is not, I published it now and linked it to the PR branch :D

**Review by atanasdinov — APPROVED** [review]
Tested both k3s and RKE2 clusters configured in EIB. All cases seem to work as expected. Thanks and great work!

**Comment by hardys** [comment]
I upgraded to 0.14.3 and re-deployed a CAPI cluster via Metal3 and all worked:

```
shardy@localhost:~/metal3-demo-files> helm list -n metallb-system
NAME   	NAMESPACE     	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
metallb	metallb-system	2       	2024-03-07 11:51:42.708493747 +0000 UTC	deployed	metallb-0.14.3	v0.14.3    

shardy@localhost:~/metal3-demo-files> kubectl get bmh
NAME             STATE         CONSUMER                            ONLINE   ERROR   AGE
controlplane-0   provisioned   sample-cluster-controlplane-lpqfq   true             19h
worker-0         provisioned   sample-cluster-workers-lv2cr        true             19h
```

**Review by hardys — APPROVED** [review]

**Pull request merged**
